function add_game_shared_sources()
  add_files("$(projectdir)/game/shared/*.cpp")
  add_files("$(projectdir)/game/shared/entities/*.cpp")
  add_files("$(projectdir)/game/shared/entities/*.cpp")
  add_files("$(projectdir)/game/shared/entities/items/*.cpp")
  add_files("$(projectdir)/game/shared/entities/weapons/*.cpp")
  add_files("$(projectdir)/game/shared/loaders/*.cpp")
  add_files("$(projectdir)/game/shared/networking/*.cpp")
  add_files("$(projectdir)/game/shared/player_movement/*.cpp")
  add_files("$(projectdir)/game/shared/saverestore/*.cpp")
  add_files("$(projectdir)/game/shared/scripting/AS/*.cpp")
  add_files("$(projectdir)/game/shared/sound/*.cpp")
  add_files("$(projectdir)/game/shared/ui/hud/*.cpp")
  add_files("$(projectdir)/game/shared/utils/*.cpp")
end
